name: 'Images Config'
description: 'Feature holding config for D8 Images presentation.'
package: Custom
type: module
core: 8.x
dependencies:
  - field
  - file
  - image
  - menu_ui
  - node
  - options
  - path
  - svg_image
  - user
version: 8.x-1.0
